//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordGenerator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordContainer
    {
        public string Nazwa { get; set; }
        public string Haslo { get; set; }
    }
}
